
export const all_routes = {
    //// page no login 
    formLogin: "/login",
    forgotPaswword: "/forgot-password",
    formVerifyCode: "/verify-code",
    formVerifyCode2: "/verify-code2",
    formResetPassword: "/form-resetpassword",
    register: "/register",

    //// page login success
    dashbord: "/dashbord",
    pageNotFound: "/*",
    Book: "book",
    UserList: "userlist",
    RoleList: "rolelist",
    permission: "permissions/:id",
    Profile: "myprofile",
    Product: "product",
    Stock: "stock",
    StockMovement: "stock-movement",
    StockAdjustment: "stock-adjustment",
    StockReturn: "stock-return",
    Branch: "branch",
    Category: "category",
    Discount: "discount",
    LowStock: "lowstock",
    SaleProduct: "sale-product",
    OrderList: "order-list",
    Member: "member",
    Staff: "staff",
    Supplier: "supplier",
    AllLeaveRequest: "all-leave-request",
    MyLeaveRequest: "my-leave-request",
    LeaveType: "leave-type",
    PointSetting: "point-setting",
    testGhost: "/test-ghost",
}